// <auto-generated />
namespace ASPNETMVC_Group1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Authen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authen));
        
        string IMigrationMetadata.Id
        {
            get { return "202107230210539_Authen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
